ethcert_blockchain/ethcert_blockchain/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.conf import settings
from django.contrib import admin
from main_web_portal import views
from django.conf.urls.static import static

# error views
handler404 = 'main_web_portal.views.handler404'
handler500 = 'main_web_portal.views.handler500'

urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^main_web_portal/',include('main_web_portal.urls')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ethcert_blockchain/main_web_portal/urls.py
from main_web_portal import views
from django.conf.urls import include, url


# SET THE NAMESPACE!
app_name = 'main_web_portal'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    url(r'^transaction/$', views.transaction, name='transaction'),
    url(r'^team/$', views.team, name='team'),
    url(r'^search/$', views.view_cert, name='view_cert'),
    url(r'^dashboard/getDetails', views.personalDetails, name="personalDetails"),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/sent$', views.dashboard_sent, name='dashboard_sent'),
    url(r'^dashboard/received$', views.dashboard_received, name='dashboard_received'),
    url(r'^verify1/$', views.authForm1, name='verify1'),
    url(r'^verify2/$', views.authForm2, name='verify2'),
    url('updatePic/$', views.updateProfilePic, name='updatePic'),
    url('updateEthAddress/$', views.updateEthAddress, name='updateEthAddress'),
]

ethcert_blockchain/main_web_portal/models.py
from django.db import models
from django.contrib.auth.models import User
from background_tasks.models import Certificate
import time, os

# Use Singapore timezone
os.environ['TZ'] = 'Asia/Singapore'
time.tzset()

# Create your models here.
class UserProfile(models.Model):
    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User)

    # Add any additional attributes
    #transaction_list = ArrayField(models.CharField(max_length=64), default=list)

    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    # field for lvl1 verification code
    verification_code_lvl_1 = models.CharField(default="", max_length = 64)
# field for lvl2 verification code
    verification_code_lvl_2 = models.CharField(default="",max_length = 64)

    # address
    address = models.CharField(default="NA",max_length = 64, null=True, blank=True)

    # website
    url = models.CharField(default="NA",max_length = 64, null=True, blank=True)

    # authentication parameters
    auth1 = models.BooleanField(default=False)
    auth2 = models.BooleanField(default=False)

    #Ethereum address
    eth_address = models.CharField(default="Not Setup",max_length = 64)

    # Certificates
    sent_certificates = models.ManyToManyField(Certificate,
                                               related_name="sent_certificates",
                                               blank=True)

    received_certificates = models.ManyToManyField(Certificate,
                                                   related_name="received_certificates",
                                                   blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

    def getVerificationCode1(self):
        return str(self.verification_code_lvl_1)

    def setVerificationCode1(self, code):
        self.verification_code_lvl_1 = code;

    def getVerificationCode2(self):
        return str(self.verification_code_lvl_2)

    def setVerificationCode2(self, code):
        self.verification_code_lvl_2 = code;

    def getAddress(self):
        print(self.address)
        return (self.address)

    def setAddress(self,address):
        self.address = address

    def setUrl(self,url):
        self.url = url

    def getUrl(self):
        print(self.url)
        return (self.url)

    def isAuthenticated1(self):
        return self.auth1

    def isAuthenticated2(self):
        return self.auth2

    def setAuthenticated1(self):
        self.auth1 = True;

    def setAuthenticated2(self):
        self.auth2 = True;

    def setEthAddress(self, address):
        self.eth_address = address

    def getEthAddress(self):
        return self.eth_address

    def getSentCertificates(self):
        certs = self.sent_certificates.all()
        output = []

        for cert in certs:
            data = {}
            data['certificate_id'] = cert.certificate_id
            data['sender_address'] = cert.getSenderAddress()
            data['sender_proof'] = cert.sender_proof
            data['receiver_address'] = cert.getReceiverAddress()
            data['receiver_proof'] = cert.receiver_proof
            data['description'] = cert.description
            int_time = cert.create_time
            data['create_time'] = time.strftime('%A %b %d %Y %H:%M:%S GMT%Z',
                                                time.localtime(int_time))

            output.append(data)

        return output

    def getReceivedCertificates(self):
        certs = self.received_certificates.all()
        output = []

        for cert in certs:
            data = {}
            data['certificate_id'] = cert.certificate_id
            data['sender_address'] = cert.getSenderAddress()
            data['sender_proof'] = cert.sender_proof
            data['receiver_address'] = cert.getReceiverAddress()
            data['receiver_proof'] = cert.receiver_proof
            data['description'] = cert.description
            int_time = cert.create_time
            data['create_time'] = time.strftime('%A %b %d %Y %H:%M:%S GMT%Z',
                                                time.localtime(int_time))

            output.append(data)

        return output


    # Meta class to configure options
    # https://docs.djangoproject.com/en/1.11/ref/models/options/
    class Meta:
        managed = True

ethcert_blockchain/main_web_portal/forms.py
from django import forms
from django.contrib.auth.models import User
from main_web_portal.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    class Meta():
        model = User
        fields = ('username','email','password')
        help_texts = {
            'username': None,
            'email': None,
        }
        labels = {
            'username': 'Username',
            'email':'Email',
        }
        widgets = {
            'username': forms.TextInput({'placeholder': 'User name'}),
            'email': forms.TextInput({'placeholder': 'example@domain.com'}),
        }


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('profile_pic',)


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    class Meta():
        fields = ('username','password',)
        widgets = {
            'username': forms.TextInput({'placeholder': 'User name'}),
        }

ethcert_blockchain/main_web_portal/views.py
from main_web_portal.forms import UserForm, UserProfileInfoForm
from django.core.mail import send_mail, EmailMessage

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from faker import Faker
from main_web_portal.models import UserProfile
from django.contrib.auth.models import User


# Create your views here.
def index(request):
    return render(request, "main_web_portal/index.html")


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return render(request, "main_web_portal/index.html")


def register(request):
    registered = False

    if request.method == 'POST':
        password = request.POST.get('password')
        confirmPassword = request.POST.get('passwordConfirm')
        if (password != confirmPassword):
            messages.error(request, 'Passwords do not match')
            user_form = UserForm()
            return render(request,'main_web_portal/registration.html',
                                  {'user_form':user_form,
                                   'registered':registered})

        # Get info from "both" forms
        # It appears as one form to the user on the .html page

        user_form = UserForm(data=request.POST, label_suffix='')
        # print(user_form.cleaned_data)

        #print(user_form.cleaned_data)
        # Check to see both forms are valid
        if user_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = UserProfile()

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            # if 'profile_pic' in request.FILES:
            #     print('found it')
            #     # If yes, then grab it from the POST form reply
            #     profile.profile_pic = request.FILES['profile_pic']
            profile.profile_pic = "profile_pics/default-profile-pic.jpg"

            fakeGenerator = Faker()
            vercode1 = fakeGenerator.bban()
            print("Profile auth code 1 is : " + vercode1)

            vercode2 = fakeGenerator.bban()
            print("Profile auth code 2 is : " + vercode2)

            profile.setVerificationCode1(vercode1)
            profile.setVerificationCode2(vercode2)
            print('Successfully registered')
            print("Get Verification Code 2: " + profile.getVerificationCode1())
            print("Get Verification Code 1: " + profile.getVerificationCode2())

            profile.save()
            # Registration Successful!
            registered = True

            email = EmailMessage(
                            'ETHCERT Verification Code',
                            'Hi ' + str(profile.user.username) + ',\nThank you for registering.\nYour verification code is ' +
                            str(vercode1) + "\nLogin to ETHCERT Dashboard to continue.\n\nBest Regards,\nETHCERT Team",
                            'ETHCERT TEAM' +'<sender@gmail.com>',
                            [profile.user.email],
                        )

            email.send()
            print("Email sent Successfully")
            return render(request,'main_web_portal/registration.html',
                                  {'username':profile.user.username, 'email':profile.user.email,
                                   'registered':registered})

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors)


    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        #profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.

    return render(request,'main_web_portal/registration.html',
                          {'user_form':user_form,
                           'registered':registered})



def user_login(request):
    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        User = authenticate(username=username, password=password)

        # If we have a user
        if User:
            # Check it the account is active
            if User.is_active:
                # Log the user in.
                login(request, User)
                # Send the user back to some page.
                # In this case their homepage.
                context = getUserContext(User)
                return dashboard(request)
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            messages.error(request, 'Username or Password not correct')
            return render(request, 'main_web_portal/login.html', {})

    else:
        # Nothing has been provided for username or password.
        return render(request, 'main_web_portal/login.html', {})


@login_required
def transaction(request):
    return render(request, "main_web_portal/transaction.html")


def team(request):
    return render(request, "main_web_portal/ourTeam.html")


def view_cert(request):
    if request.method == 'POST':
        # handle empty fields in javascript
        search_query = request.POST.get('searchtext')
        print(representsInt(search_query))
        if (representsInt(search_query)):
            print("clicked, searching {}".format(search_query))
            return render(request, 'main_web_portal/viewCertificate.html',
                          {"certID": search_query})

        else:
            print("clicked, searching profile{}".format(search_query))
            userObject= User.objects.filter(username = search_query)
            print(userObject.count())
            if (userObject.count() != 0):
                print("user found: " + str(userObject[0]))
                profile = UserProfile.objects.filter(user = userObject[0])[0]
                print("hello" + str(profile))
                context = getUserContext(userObject[0])
                context['NA'] = False
                return render(request,'main_web_portal/publicProfile.html',context)

            else:
                context = dict()
                context['NA'] = True
                return render(request,'main_web_portal/publicProfile.html',context)


@login_required
def dashboard(request):
    User = request.user
    context = getUserContext(User)
    print("getting ethereum address: " + context['ethAddress'])
    return render(request, 'main_web_portal/dashBoard.html', context)


@login_required
def dashboard_sent(request):
    User = request.user
    context = getUserContext(User)

    return render(request, 'main_web_portal/dashBoard_sent.html', context)


@login_required
def dashboard_received(request):
    User = request.user
    context = getUserContext(User)

    return render(request, 'main_web_portal/dashBoard_received.html', context)


def handler404(request):
    return render(request, 'main_web_portal/404.html', status= 404)


def handler500(request):
    return render(request, 'main_web_portal/500.html', status= 500)


def getUserContext(User):
    profileList = UserProfile.objects.filter(user = User)
    profile = profileList[0]
    #print(profile.isAuthenticated1())
    picForm = UserProfileInfoForm()

    context = {'username' : profile.user.username,
               'isAuth1': profile.isAuthenticated1(),
               'isAuth2': profile.isAuthenticated2(),
               'email': profile.user.email,
               'profile_pic': profile.profile_pic.url,
               'ethAddress': profile.getEthAddress(),
               'picForm':picForm,
               'address':profile.getAddress(),
               'url': profile.getUrl(),
               'sent_certificates': profile.getSentCertificates(),
               'received_certificates': profile.getReceivedCertificates(),
              }

    return context


@login_required
def authForm1(request):
    if request.method == 'POST':
        User = request.user
        profile = UserProfile.objects.filter(user = User)[0]
        code = request.POST.get('authCode1')
        print(code)
        print(profile.getVerificationCode1())
        if (code == profile.getVerificationCode1()):
            profile.setAuthenticated1()
            profile.save()
            User.save()
            return dashboard(request)
        else:
            messages.error(request, 'Email Verification code incorrect')
            return render (request,'main_web_portal/authlvl1.html',{})
    else:
        return render (request,'main_web_portal/authlvl1.html',{})


@login_required
def authForm2(request):
    if request.method == 'POST':
        User = request.user
        profile = UserProfile.objects.filter(user = User)[0]
        code = request.POST.get('authCode2')
        if (code == profile.getVerificationCode2()):
            profile.setAuthenticated2()
            profile.save()
            User.save()
            return dashboard(request)
        else:

ethcert_blockchain/templates/main_web_portal/authlvl2.html
{% extends "main_web_portal/blueprint.html" %}
{% load staticfiles %}

{% block body_block %}
  <h1 class="display-4" align="center"><br></h1>
  <link rel="stylesheet" href="{%static 'multi_step_register.css'%}">
  <form id="msform" method="post">
    {% csrf_token %}
    <fieldset>
      <h2 class="fs-title">Enter Postal Verification Code</h2>
      <input class= "formInput" type="text" name="authCode2" placeholder="Code"><br>
      <br>
      <input type="submit" name="" value="Verify" class="submit action-button">
    </fieldset>
  </form>

  <div class="container">
    {% for message in messages %}
          <div class="alert alert-danger">
              <a class="close" href="#" data-dismiss="alert">×</a>
              {{ message }}
          </div>
    {% endfor %}
  </div>


{% endblock %}

ethcert_blockchain/templates/main_web_portal/blueprint.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- Need to have JQuery and Javascript for DropDown Actions to work -->
    <script
    src="http://code.jquery.com/jquery-3.1.1.js"
    integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
    crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'base_style.css'%}">

  </head>


  <body >
  	<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header" height="100">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span id = "icon-bar" class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a href="{% url 'index'%}" class="navbar-brand">ETHCERT.IO</a>
      </div>


      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                  <li><a href="{% url 'main_web_portal:dashboard'%}">DashBoard<span class="sr-only">(current)</span></a></li>
									<li><a href="{% url 'main_web_portal:transaction'%}">Award Certificate<span class="sr-only">(current)</span></a></li>
                  <li class="nav navbar-right"><a href="{% url 'main_web_portal:user_logout'%}">Log out<span class="sr-only">(current)</span></a></li>
								{% else %}
                  <li><a href="{% url 'main_web_portal:user_login'%}">Sign in<span class="sr-only">(current)</span></a></li>
                  <li><a href="{% url 'main_web_portal:register'%}">Register<span class="sr-only">(current)</span></a></li>
								{% endif %}
                <li><a href="https://rinkeby.etherscan.io/address/0x9953a35ec7b3da1c54880b4a3c401746a0f5cce8" target="_blank">BlockChain<span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'main_web_portal:team'%}">Our Team<span class="sr-only">(current)</span></a></li>
          </ul>

        <!-- SEARCH BAR -->

        <form class="navbar-form navbar-right search-bar" height="20px" method="post" action="{% url 'main_web_portal:view_cert' %}">
          {% csrf_token %}
          <div class="form-group">
            <input id="searchtext" name="searchtext" type="text" class="form-control" placeholder="Enter Cert ID or Username">
          </div>
        <button id="searchbutton" name="searchbutton" type="submit" class="btn btn-default search-btn">Search</button>
        </form>



      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- OTHER STUFF ON THE PAGE -->
  <!-- It will be generated dynamically using template tagging-->

  <!-- Need to have JQuery and Javascript for DropDown Actions to work -->

  {% block body_block %}
  {% endblock %}

</body>
</html>

ethcert_blockchain/templates/main_web_portal/dashBoard_received.html
{% extends "main_web_portal/dashBoard_template.html" %}
{% load staticfiles %}

{% block dashboard_content %}
    <link rel="stylesheet" href="{%static 'multi_step_register.css'%}">
    <link rel="stylesheet" href="{%static 'cert_table.css'%}">
    <section id="content-area">
      <div class="cards" align="center">
      <div class="col-md-12">
        <div class="card-header">
          <div class="heading" align="center">
            <h1>Received Certificates</h1>
          </div>
        </div>

        <section>
        <div class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th class="cert_header">ID</th>
                <th class="cert_header">Sender Address</th>
                <th class="cert_header">Receiver Address</th>
                <th class="cert_header">Create Time</th> 
              </tr>
            </thead>
          </table>
        </div>

        <div class="tbl-content">
          <table id="tableid" cellpadding="0" cellspacing="0" border="0">
            <tbody>
              {% for cert in received_certificates reversed %}
              <tr class="cert_row">
                <td class="cert_data" id="{{cert.certificate_id}}">{{cert.certificate_id}}</td>
                <td class="cert_data">{{cert.sender_address}}</td>
                <td class="cert_data">{{cert.receiver_address}}</td>
                <td class="cert_data">{{cert.create_time}}</td>
              </tr>
              {% endfor %}
            </tbody>

        </div>        
      </div>
      </div>
    </div>

    <script>
        var profile = document.getElementById("dashboard_profile").classList.remove("active");
        var sent = document.getElementById("dashboard_sent").classList.remove("active");
        var rec = document.getElementById("dashboard_received").classList.add("active");

  
        function addRowHandlers() {
          var table = document.getElementById("tableid");
          var rows = table.getElementsByTagName("tr");
          for (i = 0; i < rows.length; i++) {
              var currentRow = table.rows[i];
              var createClickHandler = 
                  function(row) 
                  {
                    return function() { 
                      var cell = row.getElementsByTagName("td")[0];
                      var id = cell.innerHTML;

                      // submit hidden form
                      method = "post";
                      var form = document.createElement("form");
                      form.setAttribute("method", method);
                      form.setAttribute("action", "{% url 'main_web_portal:view_cert' %}");
                      
                      // csrf token
                      var csrftoken = document.createElement("input");
                      csrftoken.setAttribute("type", "hidden");
                      csrftoken.setAttribute("name", "csrfmiddlewaretoken");
                      csrftoken.setAttribute("value", "{{ csrf_token }}");                      
                     
                      // cert id
                      var hiddenField = document.createElement("input");
                      hiddenField.setAttribute("type", "hidden");
                      hiddenField.setAttribute("name", "searchtext");
                      hiddenField.setAttribute("value", id);
                      
                      // submit
                      form.appendChild(csrftoken);
                      form.appendChild(hiddenField);
                      document.body.appendChild(form);
                      form.submit();                                              
                    };
                  };

              currentRow.onclick = createClickHandler(currentRow);
          }
      }
      window.onload = addRowHandlers();
        

        
        
    </script>

{% endblock dashboard_content %}

ethcert_blockchain/templates/main_web_portal/dashBoard_template.html
{% extends "main_web_portal/blueprint.html" %}
{% load staticfiles %}
{ % load MEDIA_URL %}

{% block body_block %}
  <h1 class="display-4" align="center"><br></h1>
  <link rel="stylesheet/less" type="text/css" href="{% static 'dashboard-style.less' %}" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/3.0.0/less.min.js" ></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
  <div class="wrapper">
    <section id="sideBar">
      <nav>
        <a id="dashboard_profile" href="{% url 'main_web_portal:dashboard' %}"><i id="dbIcon" class="fas fa-user" ></i>Profile</a>
        <a id="dashboard_sent" href="{% url 'main_web_portal:dashboard_sent' %}"><i id="dbIcon" class="fas fa-rocket"></i>Sent Certificates</a>
        <a id="dashboard_received" href="{% url 'main_web_portal:dashboard_received' %}"><i id="dbIcon" class="fas fa-archive"></i>Received Certificates</a>
      </nav>
    </section>
   
    {% block dashboard_content %}
    {% endblock dashboard_content %}


{% endblock body_block %}

ethcert_blockchain/templates/main_web_portal/issue.html
{% extends "main_web_portal/blueprint.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <h1>Issue Certificate</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ transaction_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
    </div>
  </div>

{% endblock %}

ethcert_blockchain/templates/main_web_portal/login.html
{% extends 'main_web_portal/blueprint.html' %}
{% load staticfiles %}

{% block body_block %}
  <link rel="stylesheet" href="{%static 'multi_step_register.css'%}">
  <div class="container">
    <h1 class="display-4" align="center"><br></h1>
      <form id="msform" method="post" action="{% url 'main_web_portal:user_login' %}">
        {% csrf_token %}
        <fieldset>
          <h2 class="fs-title">Enter your Login Credentials</h2>
          <input class= "formInput" type="text" name="username" placeholder="Username"><br>
          <br>
          <input class= "formInput" type="password" name="password" placeholder="Password"><br>
          <br>
          <input type="submit" name="Login" value="Login" class="submit action-button">
        </fieldset>
      </form>

      {% for message in messages %}
            <div class="alert alert-danger">
                <a class="close" href="#" data-dismiss="alert">×</a>
                {{ message }}
            </div>
      {% endfor %}
  </div>
{% endblock %}

ethcert_blockchain/templates/main_web_portal/logout.html
{% extends 'main_web_portal/blueprint.html' %}
{% block body_block %}
  <div class="container">
    <div class="landing_page">
      <h1 class="display-4" align="center"><br></h1>
      <h1>You have successfully logged in</h1>
    </div>
  </div>
{% endblock %}

ethcert_blockchain/templates/main_web_portal/registration.html
{% extends "main_web_portal/blueprint.html" %}
{% load staticfiles %}

{% block body_block %}

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
  <link rel="stylesheet" href="{%static 'multi_step_register.css'%}">
  <div class="container">
      <h1 class="display-4" align="center"><br></h1>
      {% if registered %}
      <div class="jumbotron">
        <div align="center">
          <img src="https://cdn1.iconfinder.com/data/icons/toolbar-signs/512/OK-512.png" align="middle" height="72" width="62">
        </div>
        <h1 class="display-4" align="center">Registration Success {{username}}!</h1>
        <p class="lead" align="center">Verification code sent to {{email}}</p>
        <hr class="my-4" size="30" align="center">
        <p class="lead" align="center">Login to Ethcert Dashboard to continue</p>
        <p class="lead" align="center">
          <a class="btn btn-success btn-lg" href="{% url 'main_web_portal:user_login' %}" role="button">Login</a>
        </p>
      </div>

      {% else %}
        <form id="msform" enctype="multipart/form-data" method="POST" action="{% url 'main_web_portal:register' %}">
          <fieldset>
              {% csrf_token %}
              <h2 class="fs-title">Create your account</h2>
              {% for field in user_form %}
                  <div class="fieldWrapper">
                      <div class="formInput">
                      {{ field }}
                      </div>
                  </div>
                  <br>
              {% endfor %}

            <input type="password" name="passwordConfirm" placeholder="Confirm Password" required/>
            <input type="submit" name="submit" class="submit action-button" value="Submit" />
            <br>
          </fieldset>
        </form>
      {% endif %}

      {% for message in messages %}
            <div class="alert alert-danger">
                <a class="close" href="#" data-dismiss="alert">×</a>
                {{ message }}
            </div>
      {% endfor %}
      
  </div>

{% endblock %}